Deploy main

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -38,6 +38,20 @@ jobs:
           key: ${{ secrets.EC2_KEY }}          # Private key from GitHub Secrets
           port: 22
           script: |
+
+            echo "🔧 Checking Docker installation..."
+
+            if ! command -v docker &> /dev/null; then
+            echo "Docker not found. Installing Docker..."
+            sudo yum update -y
+            sudo yum install docker -y
+            sudo systemctl start docker
+            sudo systemctl enable docker
+            sudo usermod -aG docker ec2-user
+            else
+            echo "Docker already installed ✅"
+            fi
+
             echo "Pulling latest Docker image..."
             docker pull timiscode/hair-shop-app:latest
 
